apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  resource-quota: "production"

patches:
  - target:
      kind: Deployment
      name: app-with-thimble
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app-with-thimble
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: thimble
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "200m"
                  limits:
                    memory: "512Mi"
                    cpu: "1000m"

images:
  - name: ghcr.io/inovacc/thimble
    newTag: v1.0.0
